### ISSUE TITLE
At most 1 insertion per id?

### ISSUE THREAD

**Issue by naiaden** [LanguageMachines/CLIN28_ST_spelling_correction#10]
My software currently also inserts two missing words after an existing id. In the first pass it finds a missing word after 'page1.text.div.5.p.2.s.2.w.7'. Internally I have to give this some new id, so I name it 'page1.text.div.5.p.2.s.2.w.7M'. Now in the second pass I find that after 'page1.text.div.5.p.2.s.2.w.7M' another word is lacking (for some reason). How do I handle this case? Or do you explicitely only allow at most one insertion in one place?

**Comment by proycon** [comment]
In your the JSON correction output, you simply can use ``after`` with a ``text`` that contains spaces. So yes, it is one insertion, but it can be a multi-token insertion. May require a bit of extra fiddling if you use a multi-pass approach.
