### ISSUE TITLE
Prepare for call for participation

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/CLIN28_ST_spelling_correction#5]
Things to ensure prior to call (strikethrough = done):
 * ~~Add initial validation documents to this repo (@merijnbeeksma)~~
 * ~~Manual cleanup of noise in FoLiA  (FOUTJE dummies etc) (@merijnbeeksma & @proycon)~~
 * ~~Remove observation layer (@proycon)~~
 * ~~Convert FoLiA to JSON and verify result (@proycon)~~
 * Verify instructions in README are complete (all)

**Comment by proycon** [comment]
I think the README/call should include some more text on how we evaluate participants?

**Comment by proycon** [comment]
I'm still missing the following in the README/call text:

* Text on how we evaluate participants
  * Do we expect participants to assign the right classes or will judge regardless of classes? Must be made explicit I'd say.
  * Do we provide facilities for participants to provide multiple (possibly weighted) corrections? A distinction between "best" vs "out-of-five/ten/whatever" is not uncommon in such tasks. This would need a small adaptation in the JSON format.
* Do we add a section on software development, publishing,  and promote quality & sustainability by awarding the system that complies to the guidelines most? (I can take care of that)

**Comment by proycon** [comment]
@merijnbeeksma Oh, and we should settle the issue about diacritics being considered reduntantpunctuation or not as we discussed today.

**Comment by fkunneman** [comment]
The information on software quality sounds good! I will add some lines to the evaluation section as you mention.

**Comment by fkunneman** [comment]
I checked the Readme and it seems that all information is in there. 
I also extended the description on evaluation. Could you check whether this seems okay? If this is the case, I will send out the call for abstracts with a reference to the shared task.

**Comment by proycon** [comment]
Call is out
