### ISSUE TITLE
Any news on when the 50 articles will be made available?

### ISSUE THREAD

**Issue by jvdzwaan** [LanguageMachines/CLIN28_ST_spelling_correction#7]

**Comment by fkunneman** [comment]
Hi Janneke,

We are working on it and hope to disclose the 50 articles by the end of this week. 

Best regards,
Florian Kunneman

**Comment by proycon** [comment]
(update: 10 articles have been made available now)

**Comment by proycon** [comment]
(another update: 10 more articles have just been published; so 20 in total thus-far)
